Test relop...                                   [ FAILED ]
  Case "==":
    Threw std::exception... failed
      std::exception::what(): lexer_323 is broken
Test condition...                               [ FAILED ]
  Case "true==true":
    Threw std::exception... failed
      std::exception::what(): lexer_323 is broken
Test id...                                      [ FAILED ]
  Case "a":
    Threw std::exception... failed
      std::exception::what(): lexer_323 is broken
Test qualifier...                               [ FAILED ]
  Case "static":
    Threw std::exception... failed
      std::exception::what(): lexer_323 is broken
Test assign...                                  [ FAILED ]
  Case "a = 123;":
    Threw std::exception... failed
      std::exception::what(): lexer_323 is broken
Test primary...                                 [ FAILED ]
  Case "temp":
    Threw std::exception... failed
      std::exception::what(): lexer_323 is broken
Test expression...                              [ FAILED ]
  Case "":
    Threw std::exception... failed
      std::exception::what(): std::bad_alloc
Test parameters...                              [ FAILED ]
  Case "a()":
    Threw std::exception... failed
      std::exception::what(): lexer_323 is broken
Test term...                                    [ FAILED ]
  Case "x":
    Threw std::exception... failed
      std::exception::what(): lexer_323 is broken
FAILED: 9 of 9 unit tests have failed.
